main:
    random_seed: 'nips2019'
    saved_dir: '/home/tony/Model_Genesis/models/MG/unet3d/train'

dataset:
    name: 'MGDataset'
    kwargs:
        data_dir: '/home/tony/datasets/LUNA'
        data_split_csv: '/home/tony/Model_Genesis/LUNA_split.csv'
        train_preprocessings:
            - name: 'HUNormalize'
              kwargs:
                  hu_max: 1000.
                  hu_min: -1000.
            - name: 'RandomCrop'
              kwargs:
                  size: [128, 128, 24]
        valid_preprocessings:
            - name: 'HUNormalize'
              kwargs:
                  hu_max: 1000.
                  hu_min: -1000.
            - name: 'RandomCrop'
              kwargs:
                  size: [128, 128, 24]
        # augments:
        #     - name: 'RandomElasticDeformation'
        #     - name: 'RandomHorizontalFlip'
        #     - name: 'RandomVerticalFlip'
        transforms:
            - name: 'NonLinearTransform'
              kwargs:
                  prob: 0.3
            - name: 'LocalPixelShuffling'
              kwargs:
                  x_size: 10
                  y_size: 10
                  z_size: 10
                  prob: 0.3
            - name: 'InOutPainting'
              kwargs:
                  paint_rate: 0.3
                  inpaint_rate: 0.5
            - name: 'ToTensor'
            
dataloader:
    name: 'Dataloader'
    kwargs:
        train_batch_size: 4
        valid_batch_size: 1
        shuffle: true
        num_workers: 4

net:
    name: 'MGUNet3D'
    kwargs:
        in_channels: 1
        out_channels: 1
        num_features: [32, 64, 128, 256, 512]
        
losses:
    - name: 'MSELoss'
      weight: 1.0

metrics:
    - name: 'MSE'

optimizer:
    name: 'Adam'
    kwargs:
        lr: 0.001
        weight_decay: 0
        amsgrad: false

logger:
    name: 'MGLogger'
    kwargs:
        dummy_input: [16, 1, 128, 128]

monitor:
    name: 'Monitor'
    kwargs:
        mode: 'min'
        target: 'Loss'
        saved_freq: 50
        early_stop: 0

trainer:
    name: 'MGTrainer'
    kwargs:
        device: 'cuda:0'
        num_epochs: 400
